[workspace]
resolver = "2"

members = [
  "crates/cxx-llvm",
  "crates/cxx-llvm-auto",
  "crates/cxx-llvm-build",
  "crates/cxx-llvm-build-common",
  "xtask",
]

[patch.crates-io]
# cxx-auto = { path = "../cxx-auto" }
# moveref = { path = "../moveref" }
